#spring.application.name=Bookstore-Application-Zynetic
#
#spring.datasource.url=jdbc:mysql://localhost:3306/zyneticbook?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=kiit
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true


# Application name
spring.application.name=Bookstore-Application-Zynetic

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://souptikkaran23:1234@springboot.v0ihdls.mongodb.net/?retryWrites=true&w=majority&ssl=true&sslInvalidHostNameAllowed=true

# Optional: Specify a database name (if you want to use a specific DB)
spring.data.mongodb.database=zyneticbookstore

# Logging
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Server port (optional, customize if needed)
server.port=8080
